### ISSUE TITLE
configure travis to deploy a demo

### ISSUE THREAD

**Issue by cbleek** [yawik/yavue#1]
let's configure travis to deploy a working demo using github pages

**Comment by cbleek** [comment]
@kilip the GOOGLE_API_KEY has to be added to a .env.local file. Can you do this?

**Comment by kilip** [comment]
In travis we can set that in the environment variables. Google API Key can be set in .env.local file or via environment variables. I already set that google api key via travis environment variables

**Comment by cbleek** [comment]
currently the 'dist' directory is published on the Github pages (I think). The regional search probably doesn't work because the VUE app doesn't know a Google API key. 



the [deploy'section](https://github.com/yawik/yavue/blob/master/.travis.yml#L30)  seems to make the magic.

**Comment by cbleek** [comment]
@kilip can you try to make it working

![Bildschirmfoto 2019-10-16 um 20 52 16](https://user-images.githubusercontent.com/858642/66950014-e2d5e380-f057-11e9-83bf-e2131a3789bf.png)

**Comment by kilip** [comment]
Yes, I will try to working on it today.

**Comment by kilip** [comment]
@cbleek I think all the functionality is working now, please check.

**Comment by cbleek** [comment]
works greate. Thank you.
