### ISSUE TITLE
make the API endpoint configurable

### ISSUE THREAD

**Issue by cbleek** [yawik/yavue#9]
@kilip can you make the url of the api Endpoint configurable?

https://github.com/yawik/yavue/blob/master/src/components/Yavue.vue#L134

**Comment by kilip** [comment]
It's already configurable, take a look at sample on this line:

https://github.com/yawik/yavue/blob/3b6abc127ae01adf0f20ce44534363b0591a5189/public/index.html#L12-L16

**Comment by cbleek** [comment]
I would like to set the endpoint https://www.stellenmarkt.com/de/jobs?json=1 under yavue.de.

This URL should be configurable via a .env.local configuration.

The widget feature is done in a 2nd step.

**Comment by kilip** [comment]
@cbleek travis environment variables is working now, please try to delete and create new VUE_APP_GOOGLE_API_KEY with correct value in this page:

https://travis-ci.org/yawik/yavue/settings

**Comment by cbleek** [comment]
I've created a new Google API Key. It works. Thank you
